version: '3'
services:
  web:
    container_name: appserver-${PHP_BASE_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_BASE_IMAGE: ${PHP_BASE_IMAGE}
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/web
    depends_on:
      - database
    networks:
      - yoda
  database:
    image: specbee/mariadb:latest
    ports:
      - "3310:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - yoda
networks:
  yoda:
    driver: bridge

